eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://classnine_eureka_server:8761/eureka/
  instance:
    hostname: classnine_eureka_server
